[package]
name = "seid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
rustyline = "6.1.2"